spring:
  application:
    name: journal-App
  data:
    mongodb:
      uri: mongodb+srv://Somalika:Bhuvam123@cluster0.27agbok.mongodb.net/journalApp?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080



